---
#ansible-playbook -i inventory.ini labs/check.yml 
#ansible-playbook -i inventory.ini labs/check.yml --check
- hosts: all
  tasks:
    - name: 'Fail if not run with --check'
      shell: 'exit 1'

    - name: 'Will fail even in --check mode'
      shell: 'exit 1'
      check_mode: no
